apiVersion: apps/v1
kind: Deployment
metadata:
  name: projeto-devops
  labels:
    app: fastapi
    created-by: viniciusemanuelds
  annotations:
    repository: 'https://github.com/vinicius-emanuelds/projeto-DevOps.git'
spec:
  replicas: 2
  selector:
    matchLabels:
      name: projeto-devops
      app: fastapi
  template:
    metadata:
      labels:
        name: projeto-devops
        app: fastapi
    spec:
      containers:
      - name: projeto-devops
        image: viniciusemanuelds/projeto-devops:{{tag}}
        ports:
        - containerPort: 8000
---

apiVersion: v1
kind: Service
metadata:
  name: projeto-devops
spec:
  selector:
    app: fastapi
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30000
  type: LoadBalancer

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: projeto-devops-ingress
  namespace: devops
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: projeto.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: projeto-devops
                port:
                  number: 80


